# Generated by Django 6.1.1 on 2026-09-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('Data Science', 'Data Science'), ('AIML', 'AIML'), ('ECE', 'ECE'), ('MEC', 'MEC')], max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2'), ('Unit 3', 'Unit 3'), ('Unit 4', 'Unit 4'), ('Unit 5', 'Unit 5')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('marks', models.IntegerField(choices=[(2, '2 Marks'), (4, '4 Marks'), (8, '8 Marks')])),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
